server:
  port: ${PORT:8081}

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# CRITICAL: Eureka Configuration for Railway
eureka:
  instance:
    hostname: ${RAILWAY_PUBLIC_DOMAIN:localhost}
    non-secure-port: ${PORT:8081}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.value}
    home-page-url: https://${eureka.instance.hostname}/
    status-page-url: https://${eureka.instance.hostname}/actuator/info
    health-check-url: https://${eureka.instance.hostname}/actuator/health
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.user: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG