server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 15000
    response-cache-update-interval-ms: 5000
    # THIS IS THE KEY FIX - Allow REST endpoints
    rest-api-port-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG